# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
    ]
